// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type LlmProviderModel = {
    id: string;
    provider: string;
    modelId: string;
    displayName: string;
};

export type TtsProviderModel = {
    id: string;
    provider: string;
    modelId: string;
    displayName: string;
};

export type SttProviderModel = {
    id: string;
    provider: string;
    modelId: string;
    displayName: string;
};

export type ProviderModelsResponse = {
    llm: Array<LlmProviderModel>;
    tts: Array<TtsProviderModel>;
    stt: Array<SttProviderModel>;
};

export type ListProviderModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/provider-models';
};

export type ListProviderModelsResponses = {
    /**
     * OK
     */
    200: ProviderModelsResponse;
};

export type ListProviderModelsResponse = ListProviderModelsResponses[keyof ListProviderModelsResponses];
