// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ClaimInviteCodeData, ClaimInviteCodeResponses, GenerateInviteCodesData, GenerateInviteCodesResponses, ValidateInviteCodeData, ValidateInviteCodeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const validateInviteCode = <ThrowOnError extends boolean = false>(options: Options<ValidateInviteCodeData, ThrowOnError>) => (options.client ?? client).post<ValidateInviteCodeResponses, unknown, ThrowOnError>({
    url: '/invite-codes/validate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const generateInviteCodes = <ThrowOnError extends boolean = false>(options: Options<GenerateInviteCodesData, ThrowOnError>) => (options.client ?? client).post<GenerateInviteCodesResponses, unknown, ThrowOnError>({
    url: '/invite-codes/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const claimInviteCode = <ThrowOnError extends boolean = false>(options?: Options<ClaimInviteCodeData, ThrowOnError>) => (options?.client ?? client).post<ClaimInviteCodeResponses, unknown, ThrowOnError>({ url: '/invite-codes/claim', ...options });
