// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8082/api/v1' | (string & {});
};

export type ValidateRequest = {
    code: string;
};

export type ValidateResponse = {
    token?: string;
    error?: string;
};

export type GenerateRequest = {
    count: number;
    usageBudgetSeconds?: number;
};

export type GenerateResponse = {
    codes: Array<string>;
};

export type ClaimResponse = {
    code?: string;
    error?: string;
};

export type ValidateInviteCodeData = {
    body: ValidateRequest;
    path?: never;
    query?: never;
    url: '/invite-codes/validate';
};

export type ValidateInviteCodeResponses = {
    /**
     * OK
     */
    200: ValidateResponse;
};

export type ValidateInviteCodeResponse = ValidateInviteCodeResponses[keyof ValidateInviteCodeResponses];

export type GenerateInviteCodesData = {
    body: GenerateRequest;
    path?: never;
    query?: never;
    url: '/invite-codes/generate';
};

export type GenerateInviteCodesResponses = {
    /**
     * OK
     */
    200: GenerateResponse;
};

export type GenerateInviteCodesResponse = GenerateInviteCodesResponses[keyof GenerateInviteCodesResponses];

export type ClaimInviteCodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/invite-codes/claim';
};

export type ClaimInviteCodeResponses = {
    /**
     * OK
     */
    200: ClaimResponse;
};

export type ClaimInviteCodeResponse = ClaimInviteCodeResponses[keyof ClaimInviteCodeResponses];
